version: "3"
services:
   client:
    image: egasvegas/react-integral:latest
    ports:
    - "3010:3000"
    restart: unless-stopped
    container_name: reactintegral
    environment:
      REACT_APP_PATH: http://localhost:5010/IntegralSolution/calculate

   server:
    image: egasvegas/react-integral-server:latest
    ports:
    - "5010:80"
    restart: unless-stopped
    container_name: reactintegralserver
    environment:
     ASPNETCORE_ENVIRONMENT: "Development"
